export const NATS_MODULE_OPTIONS = 'NATS_MODULE_OPTIONS';
export const NATS_SUBJECT_HANDLER = 'NATS_SUBJECT_HANDLER';
export const NATS_SUBSCRIBE_OPTIONS = 'NATS_SUBSCRIBE_OPTIONS';
export const NATS_CLIENT = 'NATS_CLIENT'; 